# Generated by Django 4.2.2 on 2023-06-19 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
                ("name", models.CharField(max_length=100, unique=True)),
                ("sub_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Eine Beschreibung für die Kategorie",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
                ("name", models.CharField(max_length=100, unique=True)),
                ("sub_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Eine Beschreibung für ein Event",
                        null=True,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_group",
                    models.IntegerField(
                        choices=[
                            (5, "kleine Gruppe"),
                            (10, "Mittelgroße Gruppe"),
                            (15, "Große Gruppe"),
                        ]
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
