# Generated by Django 4.2.2 on 2023-06-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["name"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
