# Generated by Django 4.2.2 on 2023-06-20 13:25

from django.db import migrations
from django.utils.text import slugify


def slugify_events(apps, _):
    event_model = apps.get_model("events", "Event")
    for event in event_model.objects.all():
        event.slug = slugify(event.name)
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_slug"),
    ]

    operations = [migrations.RunPython(slugify_events, migrations.RunPython.noop)]
